<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260402091213 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP INDEX idx_8421fb63bf700bd');
        $this->addSql('ALTER TABLE devices ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE devices ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER INDEX uniq_8421fb6394a4c7d7 RENAME TO UNIQ_11074E9A94A4C7D4');
        $this->addSql('ALTER TABLE motion_events ADD sum INT DEFAULT NULL');
        $this->addSql('ALTER TABLE motion_events ADD range_cm INT DEFAULT NULL');
        $this->addSql('ALTER TABLE motion_events ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE motion_events ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER INDEX idx_8905d86a94a4c7d7 RENAME TO IDX_E07925B94A4C7D4');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE devices ALTER id SET DEFAULT nextval(\'devices_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE devices ALTER id DROP IDENTITY');
        $this->addSql('CREATE INDEX idx_8421fb63bf700bd ON devices (status)');
        $this->addSql('ALTER INDEX uniq_11074e9a94a4c7d4 RENAME TO uniq_8421fb6394a4c7d7');
        $this->addSql('ALTER TABLE motion_events DROP sum');
        $this->addSql('ALTER TABLE motion_events DROP range_cm');
        $this->addSql('ALTER TABLE motion_events ALTER id SET DEFAULT nextval(\'motion_events_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE motion_events ALTER id DROP IDENTITY');
        $this->addSql('ALTER INDEX idx_e07925b94a4c7d4 RENAME TO idx_8905d86a94a4c7d7');
    }
}
